### ISSUE TITLE
missing images

### ISSUE THREAD

**Issue by samdude28** [samdude28/TigerBooz#2]
Absolut Vodka     doesn't show
Admiral Nelsons      missing image
Bacardi            misspelled (fixed)
Hendrick's           doesn't show
Ancient Age         missing image***
Evan Williams       misspelled (fixed)

**Comment by samdude28** [comment]
tequila:
1800 needs image

**Comment by samdude28** [comment]
Ketel One Vodka needs image

**Comment by samdude28** [comment]
Nolets needs image

**Comment by Bishop92t** [comment]
All these are fixed
